[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
yatra_trrl = "B8Y64wzmTott2wp5rgP1UyDgAofohU3hfTnmxkMAPFDV"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
