import {
    Connection,
    Keypair,
    PublicKey,
} from '@solana/web3.js';
import { AnchorProvider, Program } from '@coral-xyz/anchor';
import NodeWallet from '@coral-xyz/anchor/dist/esm/nodewallet.js';

// Program ID — matches declare_id! in lib.rs
export const TRRL_PROGRAM_ID = new PublicKey('9BvgVETSbpoccubSqkTZUuqaTaZVwPXzvhDi4ies88HN');

// Seeds must match the Rust program exactly
const DRIVER_REP_SEED = Buffer.from('driver_rep');

export function getDriverRepPDA(driverWallet: string): PublicKey {
    const [pda] = PublicKey.findProgramAddressSync(
        [DRIVER_REP_SEED, new PublicKey(driverWallet).toBytes()],
        TRRL_PROGRAM_ID
    );
    return pda;
}

function getProgram(connection: Connection, serverKeypair: Keypair) {
    // IDL is auto-generated by `anchor build` — imported after first build
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const idl = require('./trrl_idl.json');
    const wallet = new NodeWallet(serverKeypair);
    const provider = new AnchorProvider(connection, wallet, { commitment: 'confirmed' });
    return new Program(idl, provider);
}

/**
 * Creates the on-chain DriverRep PDA for a driver.
 * Called once when a driver first verifies their ZK identity.
 */
export async function initializeDriverRep(
    connection: Connection,
    serverKeypair: Keypair,
    driverWallet: string,
): Promise<string> {
    const program = getProgram(connection, serverKeypair);
    const driverPubkey = new PublicKey(driverWallet);
    const pda = getDriverRepPDA(driverWallet);

    // Check if already initialized — idempotent
    const existing = await connection.getAccountInfo(pda);
    if (existing) {
        return pda.toBase58();
    }

    const tx = await program.methods
        .initializeRep(driverPubkey)
        .accounts({
            driverRep: pda,
            authority: serverKeypair.publicKey,
        })
        .signers([serverKeypair])
        .rpc({ commitment: 'confirmed' });

    console.log(`[TRRL] Initialized PDA for ${driverWallet} — tx: ${tx}`);
    return pda.toBase58();
}

/**
 * Updates the driver's on-chain reputation PDA.
 * Called after every trip completion or rating submission.
 */
export async function updateDriverRepOnChain(
    connection: Connection,
    serverKeypair: Keypair,
    driverWallet: string,
    rep: {
        totalTrips: number;
        completedTrips: number;
        avgRatingX100: number;
        onTimeArrivals: number;
        zkVerified: boolean;
        sosTriggered: number;
    }
): Promise<{ signature: string; pda: string }> {
    const program = getProgram(connection, serverKeypair);
    const pda = getDriverRepPDA(driverWallet);

    // Auto-initialize if PDA doesn't exist yet
    const existing = await connection.getAccountInfo(pda);
    if (!existing) {
        await initializeDriverRep(connection, serverKeypair, driverWallet);
    }

    const tx = await program.methods
        .updateRep({
            totalTrips: rep.totalTrips,
            completedTrips: rep.completedTrips,
            avgRatingX100: rep.avgRatingX100,
            onTimeArrivals: rep.onTimeArrivals,
            zkVerified: rep.zkVerified,
            sosTriggered: rep.sosTriggered,
        })
        .accounts({
            driverRep: pda,
            authority: serverKeypair.publicKey,
        })
        .signers([serverKeypair])
        .rpc({ commitment: 'confirmed' });

    return { signature: tx, pda: pda.toBase58() };
}

/**
 * Reads the driver's reputation directly from the on-chain PDA.
 * No Yatra server needed — any platform can call this.
 */
export async function readDriverRepOnChain(
    connection: Connection,
    driverWallet: string,
): Promise<{
    score: number;
    totalTrips: number;
    completedTrips: number;
    avgRating: number;
    onTimePct: number;
    zkVerified: boolean;
    lastUpdated: string;
} | null> {
    try {
        // eslint-disable-next-line @typescript-eslint/no-require-imports
        const idl = require('./trrl_idl.json');
        // Read-only provider — no wallet needed
        const provider = new AnchorProvider(
            connection,
            { publicKey: PublicKey.default } as any,
            { commitment: 'confirmed' }
        );
        const program = new Program(idl, provider);
        const pda = getDriverRepPDA(driverWallet);

        const rep = await (program.account as any).driverRep.fetch(pda);

        const completed = Number(rep.completedTrips);
        const onTime = Number(rep.onTimeArrivals);

        return {
            score: Number(rep.score),
            totalTrips: Number(rep.totalTrips),
            completedTrips: completed,
            avgRating: Number(rep.avgRatingX100) / 100,
            onTimePct: Math.round((onTime / Math.max(completed, 1)) * 100),
            zkVerified: Boolean(rep.zkVerified),
            lastUpdated: new Date(Number(rep.lastUpdated) * 1000).toISOString(),
        };
    } catch {
        return null;
    }
}
